name: CI Workflow
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: ${{ contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
          format: ${{ contains(fromJSON('["push", "pull_request"]'), github.event_name) }}

